###
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Nvidia",
    "symbol": "N1",
    "price": 110,
    "image": "AMZN.png"
}

###

@assetId = {{ createAsset.response.body._id }}

###
GET http://localhost:3000/assets

###
GET http://localhost:3000/assets/A1

###
POST http://localhost:3000/assets/A1/dailies
Content-Type: application/json

{
  "date": "2024-12-10",
  "price": 100
}

###
GET http://localhost:3000/assets/A1/dailies

###
# @name createWallet
POST http://localhost:3000/wallets

###

@walletId = {{ createWallet.response.body._id }}

###
GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/53f7e57b-221c-4443-a63a-8625fd4cf41b

###
POST http://localhost:3000/wallets/53f7e57b-221c-4443-a63a-8625fd4cf41b/assets
Content-Type: application/json

{
    "assetId": "9d3e1bbb-d0d2-4b0a-b525-ff0b711ae154",
    "shares": 100
}

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "walletId": "{{ walletId }}",
    "assetId": "{{ assetId }}",
    "shares": 10,
    "price": 100,
    "type": "BUY"
}

###
GET http://localhost:3000/orders?walletId=fcc4de1c-f0fb-4c1e-afbb-f259f1672447