import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/nav-bar";
import { ToastContainer } from "@/components/toast-container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col">
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
